### PR TITLE
Replace `libre_wolf` with `librewolf` and cleanup typography

### PR DESCRIPTION
**Pull request by mmvanheusden**
Currently. LibreWolf is mentioned everywhere as `libre_wolf`. This is inconsistent, as Firefox is mentioned as `firefox`.

I also updated Cargo dependencies and improved some typography here and there.
Thank you for your project

### CODE REVIEW

**Comment by thewh1teagle** [comment]
I'm glad the library helped you
Thank you very much for the contribution!

**Comment by ShayBox** [comment]
This is a breaking change that broke backwards compatibility with 0.3 and should have been in 0.4 to prevent any projects depending on 0.3 from breaking.

**Comment by thewh1teagle** [comment]
@ShayBox 
I'm not use to follow that so I forgot to follow semver convention.
Thanks for explaining it really helps, I'll yank, republish, retag and update here when finished :)

**Comment by mmvanheusden** [comment]
Yes, I have also marked the commit with a `!` to symbolize a breaking change. See https://www.conventionalcommits.org.

> Thanks for explaining it really helps, I'll yank, republish, retag and update here when finished :)

Awesome!

**Comment by thewh1teagle** [comment]
I published new version `v0.4.0` in [crates.io](https://crates.io/crates/rookie) and [pypi.org](https://pypi.org/project/rookiepy/) 
Thanks for bringing this to my attention!

**Comment by mmvanheusden** [comment]
> I didn't know about Conventional Commits, thank you 👍

Every day we learn something new :smile: 


> I published new version `v0.4.0` in [crates.io](https://crates.io/crates/rookie) and [pypi.org](https://pypi.org/project/rookiepy/)

:+1:

**Pull request merged**
